version: '3.1'
services:
    server:
        container_name: portfolio-server
        image: node:20
        stdin_open: true
        ports:
            - 3005:3000
        volumes:
            - ./:/var/www/
        command: ["sh", "-c", "cd /var/www && yarn && yarn run build && yarn start"]
        restart: on-failure